name: Build & publish drill-hook artifacts
on:
  push:
    branches:
      - master

jobs:
  build_macos_distr:
    name: (Macos platform)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish
        run: gradle --no-daemon publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m

  build_windows_distr:
    name: (Windows platform)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish
        run: gradle publishMingwX64PublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  build_linux_distr:
    name: (LINUX platform)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish
        run: gradle publishLinuxX64PublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

