name: Build & publish drill artifacts
on:
  push:
    tags:
      - 'v*'

jobs:
  check_for_win:
    name: (Windows platform)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Gradle Cache
        id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v1
      - name: Konan Cache
        id: cache-konan
        uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: |
          gradle -si jvmTest
check_for_linux:
    name: (LINUX platform)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Gradle Cache
        id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v1
      - name: Konan Cache
        id: cache-konan
        uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: |
          gradle -si jvmTest